[package]
name = "qrgode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.12.0"
graphics_buffer = "0.6.0"
piston2d-graphics = "0.30.0"
